### PR TITLE
v1.1 -

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/coverage_uniformity_report/2)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/coverage_uniformity_report/2)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[sambamba_coverage_uniformity_dxapp/src/code.sh, line 49 at r1](https://reviewable.io/reviews/moka-guys/coverage_uniformity_report/2#-M-yzEi_AR05PbV1fZ3l:-M-yzEi_AR05PbV1fZ3m:b9otpy) ([raw file](https://github.com/moka-guys/coverage_uniformity_report/blob/d1a001614c5cee352af3e81ddf0f96c0254c39b6/sambamba_coverage_uniformity_dxapp/src/code.sh#L49)):*
> ```Shell
>     # The docker -v flag mounts a local directory to the docker environment in the format:
>     #    -v local_dir:docker_dir
>     docker run -v /home/dnanexus:/home --rm graemesmith/uniform-coverage Rscript "/src/sambamba_exon_coverage.R"  "/home" /home/${outdir} ".sambamba_output.bed"
> ```

None of these inputs are explained

**Comment by Graeme-Smith** [comment]
___
*[sambamba_coverage_uniformity_dxapp/src/code.sh, line 49 at r1](https://reviewable.io/reviews/moka-guys/coverage_uniformity_report/2#-M-yzEi_AR05PbV1fZ3l:-M1UhUPt34qcLiGAYdqj:b-790ejx) ([raw file](https://github.com/moka-guys/coverage_uniformity_report/blob/d1a001614c5cee352af3e81ddf0f96c0254c39b6/sambamba_coverage_uniformity_dxapp/src/code.sh#L49)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

None of these inputs are explained
</blockquote></details>

  # -v /home/dnanexus:/home Bind the directory /home/dnanexus in the DNA Nexus instance to the /home folder in the docker app
  # This insures that all the files produced in the docker insttance will be saved before the docker instance closes
  # --rm automatically remove the container when it finishes
  # graemesmith/uniform-coverage Rscript "/src/sambamba_exon_coverage.R"  Run the R script with the following parameters:
  # "/home" = data_directory 
  # /home/${outdir} = output_directory
  # ".sambamba_output.bed" = suffix_pattern

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/coverage_uniformity_report/2)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Graeme-Smith)

___
*[sambamba_coverage_uniformity_dxapp/src/code.sh, line 49 at r1](https://reviewable.io/reviews/moka-guys/coverage_uniformity_report/2#-M-yzEi_AR05PbV1fZ3l:-M1VTgToCiurfAlQ6oaH:b-lhs69o) ([raw file](https://github.com/moka-guys/coverage_uniformity_report/blob/d1a001614c5cee352af3e81ddf0f96c0254c39b6/sambamba_coverage_uniformity_dxapp/src/code.sh#L49)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

  # -v /home/dnanexus:/home Bind the directory /home/dnanexus in the DNA Nexus instance to the /home folder in the docker app
  # This insures that all the files produced in the docker insttance will be saved before the docker instance closes
  # --rm automatically remove the container when it finishes
  # graemesmith/uniform-coverage Rscript "/src/sambamba_exon_coverage.R"  Run the R script with the following parameters:
  # "/home" = data_directory 
  # /home/${outdir} = output_directory
  # ".sambamba_output.bed" = suffix_pattern
</blockquote></details>

done, thanks

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/coverage_uniformity_report/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
